/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarPlannerRouteImport } from './../routes/_sidebar/planner'
import { Route as SidebarDcNetworkRouteImport } from './../routes/_sidebar/dc-network'
import { Route as SidebarDashboardRouteImport } from './../routes/_sidebar/dashboard'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarPlannerRoute = SidebarPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDcNetworkRoute = SidebarDcNetworkRouteImport.update({
  id: '/dc-network',
  path: '/dc-network',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDashboardRoute = SidebarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/dc-network': typeof SidebarDcNetworkRoute
  '/planner': typeof SidebarPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/dc-network': typeof SidebarDcNetworkRoute
  '/planner': typeof SidebarPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/dashboard': typeof SidebarDashboardRoute
  '/_sidebar/dc-network': typeof SidebarDcNetworkRoute
  '/_sidebar/planner': typeof SidebarPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/dc-network' | '/planner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/dc-network' | '/planner'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/dashboard'
    | '/_sidebar/dc-network'
    | '/_sidebar/planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/planner': {
      id: '/_sidebar/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof SidebarPlannerRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/dc-network': {
      id: '/_sidebar/dc-network'
      path: '/dc-network'
      fullPath: '/dc-network'
      preLoaderRoute: typeof SidebarDcNetworkRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/dashboard': {
      id: '/_sidebar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SidebarDashboardRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarDashboardRoute: typeof SidebarDashboardRoute
  SidebarDcNetworkRoute: typeof SidebarDcNetworkRoute
  SidebarPlannerRoute: typeof SidebarPlannerRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarDashboardRoute: SidebarDashboardRoute,
  SidebarDcNetworkRoute: SidebarDcNetworkRoute,
  SidebarPlannerRoute: SidebarPlannerRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
